### ISSUE TITLE
frontend crashing sometimes with the following error trace

### ISSUE THREAD

**Issue by wagmarcel** [Open-IoT-Service-Platform/oisp-frontend#153]
I cannot give a reproducible testcase but I saw it sometimes happening during E2E test.
Is this because of the new sequelize structure?

Unhandled rejection at:  Promise {
  _bitField: 18087936,
  _fulfillmentHandler0: RangeError: Invalid status code: 2404
    at ServerResponse.writeHead (_http_server.js:200:11)
    at ServerResponse.writeHead (/app/node_modules/on-headers/index.js:44:26)
    at ServerResponse._implicitHeader (_http_server.js:191:8)
    at ServerResponse.end (/app/node_modules/compression/index.js:103:14)
    at ServerResponse.send (/app/node_modules/express/lib/response.js:221:10)
    at /app/engine/handlers/v1/invites.js:60:51
    at /app/engine/api/v1/users.js:69:13
    at /app/iot-entities/postgresql/users.js:211:13
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:695:18)
    at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/app/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5),
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
Reason:  RangeError: Invalid status code: 2404
    at ServerResponse.writeHead (_http_server.js:200:11)
    at ServerResponse.writeHead (/app/node_modules/on-headers/index.js:44:26)
    at ServerResponse._implicitHeader (_http_server.js:191:8)
    at ServerResponse.end (/app/node_modules/compression/index.js:103:14)
    at ServerResponse.send (/app/node_modules/express/lib/response.js:221:10)
    at /app/engine/handlers/v1/invites.js:60:51
    at /app/engine/api/v1/users.js:69:13
    at /app/iot-entities/postgresql/users.js:211:13
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:695:18)
    at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/app/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

**Comment by oguzcankirmemis** [comment]
This is not because of the new sequelize construction. What happened was:

Tests were trying to get invites for an user that did not exist(happens when you skip the user creation part at tests) and because the user did not exist a UserNotFound response should have been sent. That being said, the current version right now somehow mixed our own internal error codes with HTTP status codes and is actually trying to set the status of the HTTP response to an invalid code(2404 to be exact, at [here](https://github.com/Open-IoT-Service-Platform/oisp-frontend/blob/a3863bc88cf91cfa370724341402c0125b154aad/public-interface/engine/handlers/v1/invites.js#L60)). What is worse is that this mistake has been done repeatedly throughout the entire file(and in some other handlers as well).

I am going to refactor these old parts and fix the issue. There is still something not right though, if the user does not exists, it should have been rejected at the authentication middleware in the first place, not here. I will check there as well if everything is working as intended.

**Comment by oguzcankirmemis** [comment]
The test case for this is also simple, a request with a non-existing user(or deleted) should be made to the defined endpoint. 

There are also many other things like this (adding component to a non existing device for example), that is probably going to result in crashing as well. My plan is to write tests for all those unexpected requests first and see what we got and act on the depending outcome.

**Comment by oguzcankirmemis** [comment]
@wagmarcel I have also found out why the request was not rejected at the authorization middleware but I am not sure if it is the correct behavior. Authorization middleware tries to parse the given token, which it can even if the user is deleted. After that it will try to find this user and if it can it will set the identity property of the request object. If it cannot find however, it will not set the identity property but also will not reject the request. It will go on with the information extracted from token even if it is not valid anymore. After that the handler at the invites.js will check if the identity property was set at the authorization middleware, if it was not it will raise an error and this was exactly the error above. However I am not sure if the authorization middleware should propagate like this. It makes more sense to me if the request gets rejected immediately. The propagating would only make sense if we do not check whether the user exists at the authorization step.

**Comment by wagmarcel** [comment]
@oguzcankirmemis yes agree - this is wrong. If the user is not found, it should not leave the Auth module.
