### ISSUE TITLE
OISP Frontend: Running OISP frontend on Old Digital Twin deployment , it fails with " password authentication failed for user "oisp_user""

### ISSUE THREAD

**Issue by yshashix** [Open-IoT-Service-Platform/oisp-frontend#282]

**Comment by yshashix** [comment]
Issue seen as :
`2023-02-24T14:13:18.104Z-info: Event Monitor Started.
Unhandled rejection at:  Promise [Object] {
  _bitField: 18087936,
  _fulfillmentHandler0: ConnectionError [SequelizeConnectionError]: password authentication failed for user "oisp_user"
      at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:182:24)
      at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:316:19)
      at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:336:19)
      at Connection.emit (events.js:400:28)
`
- Probably we can fix as creating oisp_user in Digital twin and from helm chart we can look for password

**Comment by wagmarcel** [comment]
@oguzcankirmemis please try to solve it with velero
