### ISSUE TITLE
Adding a component with a name to a device that has already a component with that name causes frontend crash

### ISSUE THREAD

**Issue by oguzcankirmemis** [Open-IoT-Service-Platform/oisp-frontend#61]
It produces this error message:
`2018-09-07T10:27:42.027680587Z Fatal Error: At least one of Components already exist
2018-09-07T10:27:42.027703511Z     at buildError (/app/lib/errorHandler/errorHandler.js:65:17)
2018-09-07T10:27:42.027708698Z     at Object.build (/app/lib/errorHandler/errorHandler.js:80:24)
2018-09-07T10:27:42.027713167Z     at /app/engine/api/v1/devices.js:398:57
2018-09-07T10:27:42.027717235Z     at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
2018-09-07T10:27:42.027721231Z     at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)
2018-09-07T10:27:42.027732839Z     at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)
2018-09-07T10:27:42.027737802Z     at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)
2018-09-07T10:27:42.027742492Z     at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:693:18)
2018-09-07T10:27:42.027746734Z     at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:133:16)
2018-09-07T10:27:42.027750835Z     at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:143:10)
2018-09-07T10:27:42.027755070Z     at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14)
2018-09-07T10:27:42.027759409Z     at runCallback (timers.js:672:20)
2018-09-07T10:27:42.027763460Z     at tryOnImmediate (timers.js:645:5)
2018-09-07T10:27:42.027767632Z     at processImmediate [as _immediateCallback] (timers.js:617:5)
`

**Comment by oguzcankirmemis** [comment]
This issue was fixed with #63, closing.
