### ISSUE TITLE
Frontend should crash if database connection fails

### ISSUE THREAD

**Issue by arkocal** [Open-IoT-Service-Platform/oisp-frontend#97]
I get the following error if database is not initialized (which is normal during startup on Kubernetes)
```
 Unhandled rejection SequelizeConnectionError: database "oisp" does not exist
    at connection.connect.err (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:128:24)
    at Connection.connectingErrorHandler (/app/node_modules/pg/lib/client.js:140:14)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Socket.&lt;anonymous&gt; (/app/node_modules/pg/lib/connection.js:125:12)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
```
The system hangs and therefore is not recreated after this. It does not retry connecting either. It should crash with an error.

**Comment by oguzcankirmemis** [comment]
Solved with #134, closing.
